# Generated by Django 5.0.6 on 2024-06-13 18:18

import django.db.models.deletion
from django.db import migrations, models

from expenses_management.models import Currency


class Migration(migrations.Migration):
    dependencies = [
        ('expenses_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(
                default=Currency.objects.get_or_create(name='Iranian Rial', code_name="IRR")[0].id,
                on_delete=django.db.models.deletion.CASCADE, to='expenses_management.currency',
            ),
            preserve_default=False,
        ),
    ]
